services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  worker:
    build: ./backend
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:7

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recon
    ports:
      - "5432:5432"